import RegisterForm from "@/components/Forms/RegisterForm";
import { redirectIfAuthenticated } from "@/util/redirectIfAuthenticated";
import Head from "next/head";
import { useRouter } from "next/router";

export const getServerSideProps = redirectIfAuthenticated;

export default function Login() {
  const router = useRouter();

  const onRegisterSuccess = () => {
    router.push("/login");
  };

  return (
    <>
      <Head>
        <title>Blog | Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="relative flex w-full flex-col justify-center gap-4 p-8 sm:px-16 md:items-center">
          <RegisterForm
            onRegisterSuccess={onRegisterSuccess}
            className="md:w-1/2 lg:w-96"
          />
        </div>
      </main>
    </>
  );
}
