import ArticleEditor from "@/components/ArticleEditor/ArticleEditor";
import { useArticleAPI } from "@/hooks/useArticleAPI";
import { articleService } from "@/services/article";
import { Article } from "@/types/article";
import Head from "next/head";
import { useRouter } from "next/router";

export async function getServerSideProps(context: any) {
  if (context.query["article_id"] == "new") {
    return {
      props: {
        new: true,
        article: {
          title: "",
          content: "",
        },
      },
    };
  }

  let article = null;
  try {
    const res = await articleService.GetById(context.params.article_id);
    article = res.data;
  } catch (e) {}
  return {
    props: {
      new: false,
      article,
    },
  };
}
interface ArticleViewProps {
  new: boolean;
  article: Article;
}

export default function ArticleView(props: ArticleViewProps) {
  const router = useRouter();
  const articleAPI = useArticleAPI();

  const ArticleEditorOnSave = (article: Partial<Article>) => {
    if (props.new) {
      articleAPI
        .Create({
          title: article.title!,
          content: article.content!,
        })
        .then((res) => {
          router.push(`/view/${res.data.article_id}`);
        })
        .catch((e) => {
          console.error(e);
        });
      return;
    }

    articleAPI
      .Update({
        id: props.article.article_id,
        title: article.title!,
        content: article.content!,
      })
      .then((res) => {
        router.push(`/view/${res.data.article_id}`);
      })
      .catch((e) => {
        console.error(e);
      });
  };

  return (
    <>
      <Head>
        <title>
          {props.new ? "New article" : `Editing ${props.article.title}`}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col gap-1 p-8 text-slate-800 sm:p-16 md:basis-2/3 lg:p-16 lg:px-32 xl:px-64">
          <ArticleEditor article={props.article} onSave={ArticleEditorOnSave} />
        </div>
      </main>
    </>
  );
}
